# Generated by Django 4.1.3 on 2022-11-03 13:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import work_cards.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCard',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.uuidmodel')),
                ('resume_nl', models.FileField(help_text='Resume in Dutch', null=True, upload_to='resumes_nl', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), work_cards.validators.FileSizeValidator(max_size=5242880)])),
                ('resume_uk', models.FileField(help_text='Resume in English', null=True, upload_to='resumes_uk', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), work_cards.validators.FileSizeValidator(max_size=5242880)])),
                ('contract_type', models.CharField(choices=[('Freelance', 'Freelance'), ('Regular', 'Regular'), ('Both', 'Both'), ('other', 'other')], default='Freelance', help_text='Contract Type', max_length=300)),
                ('available_from', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 11, 3))])),
                ('minimal_education_level', models.CharField(choices=[('No further education', 'No further education'), ('Vocational education', 'Vocational education'), ('Community College/Lower secondary education', 'Community College/Lower secondary education'), ('High school', 'High school'), ('GED (General Education Diploma)', 'GED (General Education Diploma)'), ('High school/Pre-University education', 'High school/Pre-University education'), ('Gymnasium', 'Gymnasium'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], help_text='Minimum Education Level', max_length=300)),
                ('hours_per_week', models.PositiveIntegerField(help_text='Hours per Week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemicals', 'Chemicals'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Insurance', 'Insurance'), ('Machinery', 'Machinery'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Not for Profit', 'Not for Profit'), ('Recreation', 'Recreation'), ('Retail', 'Retail'), ('Shipping', 'Shipping'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Other', 'Other')], help_text='Work Branches', max_length=300)),
                ('abroad', models.BooleanField(default=False, help_text='Work Abroad')),
                ('current_client', models.CharField(help_text='Current client', max_length=300)),
                ('looking_for', models.CharField(help_text='Looking for', max_length=300)),
                ('key_skills', models.CharField(help_text='Key skills', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_cards', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.uuidmodel',),
        ),
    ]
